### ISSUE TITLE
BUG: Observed time incorrect

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#138]
![image](https://user-images.githubusercontent.com/39256978/50591429-4bbce800-0e98-11e9-91c3-3f7427cdcf95.png)

**Comment by samijuhani** [comment]
https://dev-transitlog.hsldev.com/journey/20190102/1325/4560/2?line.lineId=4560&route.routeId=4560&route.direction=2&mapBounds=24.97612953186035%2C60.24119576602376%2C25.041360855102543%2C60.258764400428085&time=13%3A51%3A16&stop=1382135&tab=journeys&vehicle=0012%2F01509

**Comment by danieldunderfelt** [comment]
It looks like the vehicle changed it's next_stop_id much later, in Kontula. Since that is the only reference we have to the stops in the hfp data, it is used to calculate when the vehicle passed by the stop. If the data is wrong then things like this happen.
The vehicle has the Malmi station stop ID as the next_stop_id as far as in Kontula: 
![deepinscreenshot_select-area_20190103054500](https://user-images.githubusercontent.com/3145668/50623169-db57aa80-0f1b-11e9-83df-7deb7439f35f.png)
That's why the calculated drive-by times are wrong. We could move to calculating the times from the stop radiuses like the official measurements, that would fix this.

**Comment by samijuhani** [comment]
Maybe we should just wait for events for this? And use "Not available" or something when these kind of problems.

**Comment by danieldunderfelt** [comment]
Yeah absolutely, the plan is to wait for the events. I just meant that if we want to fix this sooner, we can do it.

**Comment by samijuhani** [comment]
closing this for now as decided to not fix for now while waiting events.
