### ISSUE TITLE
Back button to area search

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#202]
Current
1. Draw area search, journeys on the left
2. Choose a journey from left
3. Notice it was not the correct journey
4. Need to draw again to go back to list

Should be
4. Back button to journey list without need to draw area again.

**Comment by danieldunderfelt** [comment]
I had understood the task a bit wrong, so I also made a cancel button that you can use to clear the drawn rectangle. The cancel button and the back button that I'll get started on now will be included in PR #200.

**Comment by danieldunderfelt** [comment]
Implemented such that the selected journey data can live side-by-side with the area search data, and selecting a journey from the area search list will not close the area search. The user can simply open the area tab again, and the area with all the markers remain visible on the map while inspecting the selected journey. Fixed in #200.
