### ISSUE TITLE
Duplicate route validity times

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#217]
![image](https://user-images.githubusercontent.com/39256978/52945095-a099bc80-3379-11e9-9f5e-03ee31f94f23.png)

When should be 

![image](https://user-images.githubusercontent.com/39256978/52945136-b909d700-3379-11e9-9366-3d58fe44e312.png)

**Comment by danieldunderfelt** [comment]
So the end date is wrong? I'm sure these are directly from the JORE export but I'll check.

**Comment by samijuhani** [comment]
Yep. Let's fix it to jore if needed

**Comment by danieldunderfelt** [comment]
I'll notify this thread when I know! Got some other stuff to work on first.

**Comment by danieldunderfelt** [comment]
This is what the JORE data says:

![deepinscreenshot_select-area_20190219090434](https://user-images.githubusercontent.com/3145668/52996207-82899600-3425-11e9-9b08-63e76d7be90c.png)

Looks like there is a stray route that starts on 28.6 and goes all the way to 2050, in addition to the one that ended on 10.2.2019. I'm not sure what the logic would be to filter this out, since the route is valid from the app's perspective and replaces the route that is valid for a shorter time. Alternatively we can set the logic to filter out routes that end on the default end date of 2050-12-31 if there is another route that ends sooner with the same start date.

We also can't remove stuff from the JORE database when importing, since that would just remove all old data that we want to keep. We can manually remove in cases such as this when it seems to be removed from the JORE master database.

**Comment by danieldunderfelt** [comment]
Fixed in #224.
