### ISSUE TITLE
Extra stop on route 551

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#236]
There is Start stop 2 times on this route for some reason. Not seeing this on other services.

https://dev-transitlog.hsldev.com/journey/20190305/075800/2551/2/0?vehicle=12%2F1104&live=false&mapView=60.168818931420915%2C24.804409146308902%2C18&line.lineId=2551&route.routeId=2551&route.direction=2&time=07%3A58%3A00&journeyDetailsOpen=true&sidePanelVisible=true&mapOverlays=Stop+radius 

![image](https://user-images.githubusercontent.com/39256978/53802932-d7f89380-3f4b-11e9-89ea-715380962ace.png)

**Comment by samijuhani** [comment]
2231225 is the correct one. 2231221 should not be there.

**Comment by danieldunderfelt** [comment]
How should route segments be validated? I think what happened is that there is a route segment with that stop valid during this time, so it got included in the list. The segments are grouped by stop before being validated, so different stops can be valid at the same time. I'll try grouping per stop index instead and see if that fixes it, since the stops presumably have the same index.

**Comment by samijuhani** [comment]
Same kind of problem with 1056, both directions. Route has and will changed there.

https://dev-transitlog.hsldev.com/journey/20190306/063400/1056/2/0?vehicle=18%2F627&live=false&date=2019-03-06&time=06%3A34%3A00&line.lineId=1056&route.routeId=1056&route.direction=2&mapView=60.19002272974871%2C24.98046398162842%2C15

![image](https://user-images.githubusercontent.com/39256978/53859841-afbe7280-3fe7-11e9-992c-8ce66542560f.png)

**Comment by danieldunderfelt** [comment]
All systems are a bit messed up on route 1056. This is as good as I can get it. Many buses also turn in to the side street before the Agroksenkuja pysäkki, but afaik they should not.

![deepinscreenshot_select-area_20190307062042](https://user-images.githubusercontent.com/3145668/53932255-6599c780-40a1-11e9-865b-0fcb4e3aec04.png)

As the picture shows, the HFP system also thinks that it should stop at Kalasatama metro station instead of the stop that it actually went to. This is why the stops lack observed data.

**Comment by danieldunderfelt** [comment]
The story seems to be completely different when I change the date to today, so there is still some work to be done. But the data is majorly messed up for this route.

**Comment by samijuhani** [comment]
Working ok now
