### ISSUE TITLE
788 direction 2 data missing

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#243]
Direction 1 fine though. Must be our problem. Journeys have been driven. https://dev-transitlog.hsldev.com/?vehicle=&live=false&date=2019-03-08&time=07%3A54%3A14&mapView=60.28664190154048%2C25.30288696289063%2C11&line.lineId=9788&route.routeId=9788&route.direction=2

**Comment by danieldunderfelt** [comment]
From a quick check I noticed that the originStop, which is the basis of the initial journey list request, is missing. I'll investigate why that is, and I think fixing that will solve this issue.

**Comment by danieldunderfelt** [comment]
I investigated, and this journey hasn't gone very smoothly:

http://localhost:3000/journey/20190308/064500/9788/2/0?vehicle=18%2F242&areaBounds=&mapView=60.36516679014803%2C25.525016784667972%2C11&live=false&date=2019-03-08&time=07%3A11%3A00&tab=area-journeys&route.routeId=9788&route.direction=2&line.lineId=9788&stop=9228211

None of the events from today have a next_stop_id matching the origin stop for direction 2, which is why they don't show up in the Journeys list. I query for the departure event from the origin stop directly from the HFP api so that the UI wouldn't have to calculate it, which is why events need this data to be visible in the list. For some parts of 9788's journey the next_stop_id was simply null, but there are hfp events from the whole journey which can be viewed by scrolling the time slider.

**Comment by samijuhani** [comment]
Reported to Tieto

**Comment by samijuhani** [comment]
For a reason I don't know, it has been specified that outside HSL area next stop id shall be NA in HFP. HFP 2.0 events will fix this though so no actions for now.

**Comment by samijuhani** [comment]
Most probably the reason is that we did not map stops to outside route parts at the time hfp was specified but since then things have changed and there are stops nowadays. We'll change 2.0 spec to include this information.
