### ISSUE TITLE
All journeys tab - arrival times to last stop enhancement

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#288]
Add switcher to https://github.com/HSLdevcom/transitlog-ui/issues/256 that changes all first stop departure time to -> arrival times for last stop.

![image](https://user-images.githubusercontent.com/39256978/56202891-b3b0cc00-604c-11e9-8d07-c1eacbc8ddb4.png)

**Comment by danieldunderfelt** [comment]
I started to look at this, but querying for the departure from the first stop is a lot faster than the last stop arrival when we're loading a week's worth of departures at a time. It will become much easier with HFP 2 since it has the current_stop_id info which will enable us to query for either the arrival or the departure just as easily. So I would suggest we wait with this until HFP 2 arrives.
