### ISSUE TITLE
Stop disappears when zooming in

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#325]
https://drive.google.com/file/d/1Mdbts_FHh0sWBHpi6VzYE-0CT2LKLqO3/view

**Comment by danieldunderfelt** [comment]
This is because the StopLayer with all stops will start loading at that zoom level, but you zoomed back out before it had finished loading. Give it a moment, especially now when the cache is empty.

The single stop is visible in more distant zoom levels as a stop marker separate from the stop layer if a stop is selected, but since the same marker would be loaded in with the stop layer they are not visible at the same time.

**Comment by danieldunderfelt** [comment]
Sure, I could make the transition more smooth, but usually the stops are cached and the layer will load almost instantly so it's not a big problem.
