### ISSUE TITLE
Deadruns on vehicle search should obey traffic day

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#436]
Draws to map data from 10.10. 02:00 even though possible to look only from 4:30.

![image](https://user-images.githubusercontent.com/39256978/66559960-09c77d80-eb5f-11e9-91a1-230f38edd93a.png)

https://reittiloki.hsl.fi/?vehicle=0012%2F1523&mapView=60.2082289956193%2C24.940795891452584%2C12&time=04%3A30%3A00

**Comment by danieldunderfelt** [comment]
The slider only changes if there is a selected journey or area search results. Otherwise it goes from 4:30 to 28:30. The unsigned events are fetched from the selected day, starting at midnight and ending at 4:30 the next day.

What we should probably do is extend the slider to start at midnight by default. There hasn't been a good reason do to so until now.

**Comment by samijuhani** [comment]
Or fetch data from only starting 4:30. Could this make it faster also as less data?

**Comment by danieldunderfelt** [comment]
Modified the data to fetch between 4.30 of the current day and 4:30 of the next day. I don't think it has a noticeable impact on query speed, sadly.

**Comment by samijuhani** [comment]
Works in stage.
