### ISSUE TITLE
Add more information for missing data of journey

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#461]
Instead of "Ei tietoja" tell how much approx is missing.

**Comment by danieldunderfelt** [comment]
What I suggested was a "health" indicator for selected journeys. Fetching all events for all journeys per day per route would take forever. "Ei tietoja" means that the departure event for the journey was not found, since that's all we're querying for in the departure list and I really wouldn't query for more.

But once a journey is selected and all the events are fetched we can analyze the found events and give a health score to the HFP stream. The user can consider this if they are making decisions based on the data.

**Comment by samijuhani** [comment]
Ok. Maybe we change "Ei tietoja" for "Tietoja puuttuu" or something for now and look at this later.

**Comment by danieldunderfelt** [comment]
Journey health implemented, testable in dev.

**Comment by samijuhani** [comment]
Still need to accept "PAS" as valid event.

if PAS
then no need for ARS, PDE

**Comment by danieldunderfelt** [comment]
PAS is now used to fill in for a missing PDE event in the health check. The PAS event is also shown as a stop event on the map and in the events list. Testable in dev and stage.

**Comment by samijuhani** [comment]
Still nags about: Pysäkkitapahtumat luotu ajoneuvon paikkatiedoista pysäkille 1281112: ARS when this has been passed.

**Comment by samijuhani** [comment]
Example this journey should be 100% https://stage.reittiloki.hsl.fi/journey/20191119/055900/2550/1/0012_1337?date=2019-11-19&route.routeId=2550&route.direction=1&route.originStopId=1453287&tab=&details-tab=journey-health&mapView=60.23128556395533%2C24.93106842041016&vehicle=0012%2F1337&live=false&time=06%3A30%3A51&mapZoom=12

**Comment by danieldunderfelt** [comment]
Okay, I had misunderstood and replaced only PDE events with PAS. I'll give ARS events the same treatment.
