### ISSUE TITLE
When simulating/live map should follow vehicle

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#464]
Does not at the moment

**Comment by danieldunderfelt** [comment]
Has it ever done? I wouldn't do this, since it would force the map to center on the vehicle once a second so you can't pan away. Handling the state for when the user has panned away and it should stop following the vehicle is complicated and full of edge cases.

I can try if you want though, but it would be a time sink.

**Comment by samijuhani** [comment]
Let's leave this be.
