### ISSUE TITLE
Double results in vehicle search

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#534]
This has been looked at before but let's do it once more. 

1164 gives two of the same nobina vehicles (side and register number match?) but 964 only one?

Even stranger is 986 that gives 3 of the same vehicle.

Expected: 1 result per vehicle.

![image](https://user-images.githubusercontent.com/39256978/73336895-bb5bfd00-427b-11ea-8f3c-c7fc7b0ec803.png)

![image](https://user-images.githubusercontent.com/39256978/73336969-f78f5d80-427b-11ea-9636-ea1ffd281e68.png)

**Comment by danieldunderfelt** [comment]
I'll have a look!

**Comment by danieldunderfelt** [comment]
Turns out that there are multiple vehicles with the same ID from the same operator, making the assumption that the "unique" vehicle ID would be unique false. When matching the vehicles to HFP data it is done through the vehicle ID which is why the same vehicle is shown in the list (same registry number).

Many things in Reittiloki assume that the vehicle ID is unique, so we need to figure out a way to handle this.

**Comment by danieldunderfelt** [comment]
We are looking into getting a source for the times when the vehicles were in service.

**Comment by danieldunderfelt** [comment]
The vehice records were invalid in the data, so this issue is done for now. We just have to clean up the doubles from the database once the source data is correct.

**Comment by samijuhani** [comment]
Data problem in Kalustorekisteri. Trying to get ithe data right in there.
