### ISSUE TITLE
If doors are in "failed" UI should say door data is not available instead of "doors not opened"

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#559]
Ovet eivät auenneet -> Ovitietoa ei saatavilla

![image](https://user-images.githubusercontent.com/39256978/75766777-57c96180-5d4a-11ea-8d22-c534e1624841.png)

**Comment by samijuhani** [comment]
![image](https://user-images.githubusercontent.com/39256978/75766835-6e6fb880-5d4a-11ea-9e26-8a5204a47c7a.png)

**Comment by samijuhani** [comment]
This also with Ferry, U-bus, etc.

**Comment by samijuhani** [comment]
Checked ferry and seems to work as supposed.

**Comment by samijuhani** [comment]
Oh found a problem. This journey has few door events = doors are working, should not say doors are not available, should say only when 0 door events are there.

**Comment by danieldunderfelt** [comment]
I'm not sure what you mean. Where does it say the wrong thing? The journey health check is the only place where the whole journey is considered, and will say "unavailable" (after my next update) when no door events were found. All other places that mention doors only display the door status at a specific stop.

**Comment by samijuhani** [comment]
Forgot the link I see :D https://dev.reittiloki.hsl.fi/journey/20200624/055000/1023/2/0012_1614?date=2020-06-24&mapView=60.19531060556565%2C24.928429126739506&mapZoom=15&stop=1173148&terminal=&tab=timetables&route.routeId=1023&route.direction=2&route.originStopId=&vehicle=0012%2F1614&live=false&details-tab=journey-events&mapOverlays=Stopped+vehicle%2CTerminals&time=06%3A00%3A37&journeyEventFilters=TIMING_STOP_ARS%2CPLANNED

![image](https://user-images.githubusercontent.com/39256978/85656053-fb070380-b6b8-11ea-9582-10b1ed07b1c9.png)

**Comment by danieldunderfelt** [comment]
The problem here is that the stop event elements are only concerned with ONE event, so they don't know if there is door data from other parts of the journey. The journey health module was created specifically for analyzing all the data as a whole and is much better suited for determining if the door sensors work.

The stop events only tell you if the doors opened on that stop or not, and the journey health module tells you if the door sensors worked or not. It is possible to tell each event wheter or not there were any door events for the journey, but it's not their job to know and I wouldn't want to do it just to slightly change a small text in the UI. I think the current wording works for both cases.
