### ISSUE TITLE
1002/1 missing last two stops

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#578]
Linjan 1002/1 kaksi viimeistä pysäkkiä puuttuu reitin kuvauksesta. Yksittäisen lähdön valinnalla ne tulevat esiin. Vastasuunnassa ei ole ongelmia.

https://reittiloki.hsl.fi/?date=2020-04-16&mapView=60.198607823265036%2C24.933139085769657&route.routeId=1002&route.direction=1&route.originStopId=1090416&tab=journeys&details-tab=route-stops&mapZoom=16&vehicle=&live=false&time=06%3A32%3A00&journeyEventFilters=TIMING_STOP_ARS%2CTERMINAL_ARS%2CDEPARTURE%2CPLANNED

![image](https://user-images.githubusercontent.com/39256978/79420572-d9efab80-7fc1-11ea-8ac3-ea8401d337c1.png)

![image](https://user-images.githubusercontent.com/39256978/79420633-f7247a00-7fc1-11ea-9bd7-c9d3c266ddbd.png)

**Comment by danieldunderfelt** [comment]
This is now fixed in dev and stage!

https://dev.reittiloki.hsl.fi/?date=2020-04-16&mapView=60.198603327522676%2C24.933139085769657&route.routeId=1002&route.direction=1&route.originStopId=1090416&tab=journeys&details-tab=route-stops&mapZoom=16&vehicle=&live=false&time=06%3A32%3A00&journeyEventFilters=TIMING_STOP_ARS%2CTERMINAL_ARS%2CDEPARTURE%2CPLANNED&mapOverlays=Stopped+vehicle%2CTerminals
