### ISSUE TITLE
615/1 extra stops after Aviapolis

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#579]
615 linjalla ylimääräisiä (normaalin reitin) pysäkkejä Aviapoliksen jatkeeksi. Reitti katkaistu Aviapolikselle 14.4. alkaen, muutos tehty 13.4.

https://reittiloki.hsl.fi/?date=2020-04-16&mapView=60.30305604304719%2C24.96806144714356&route.routeId=4615&route.direction=1&route.originStopId=1020119&tab=journeys&details-tab=route-stops&mapZoom=14&mapOverlays=Stopped+vehicle%2CTerminals&live=false

![image](https://user-images.githubusercontent.com/39256978/79420678-14594880-7fc2-11ea-8175-00dad517ee63.png)

**Comment by danieldunderfelt** [comment]
This is now fixed in dev and stage:

https://stage.reittiloki.hsl.fi/?date=2020-04-16&route.routeId=4615&route.direction=1&route.originStopId=1020119&tab=journeys&details-tab=route-stops&mapZoom=12&mapView=60.234953970508286%2C24.945659637451175&vehicle=0012%2F1131&live=false&time=07%3A09%3A48&journeyEventFilters=TIMING_STOP_ARS%2CTERMINAL_ARS%2CDEPARTURE%2CPLANNED
