### ISSUE TITLE
SEQ information 

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#595]
Use SEQ for metro trains.

- One line per journey in journey view: show time for seq 1 train
- Show all trains of journey in journey information

Make it so that if other vehicle modes will get this, it shall work with them also.

**Comment by samijuhani** [comment]
![image](https://user-images.githubusercontent.com/39256978/85825180-3cb3af00-b78a-11ea-8991-6217dfbc28a4.png)

**Comment by danieldunderfelt** [comment]
Where events with seq are encountered, it now only returns the events with seq == 1 for departure listings and journey events. Chained vehicles can still be searched with vehicle search, if their vehicle Id is known, and selecting a departure from the block view will display the journey from the perspective of the vehicle. Since seq is more than 1 in this case, the journey information may not be correct so that needs to be kept in mind.

**Comment by samijuhani** [comment]
Can we get other train number here easily also
![image](https://user-images.githubusercontent.com/39256978/85852960-5b319e80-b7ba-11ea-8b78-1d4d409e9020.png)
